In [3]:
header = ["problem", "instance", "executable", "full_instance", "status", "exit_code", "real", "time", "user", "system", "memory"]

In [4]:
import re
import os
import sys
import pandas as pd
from matplotlib import pyplot as plt

df = None
for file in os.listdir("."):
    if not file.endswith(".tsv"):
        continue
    df_curr = pd.read_csv(file, sep="\t", names=header, index_col=False)
    df = pd.concat([df, df_curr]) if not df is None else df_curr

# Computing Metrics

In [5]:
# solved,par1,par10
import numpy as np


df.loc[:, "solved"] = df["status"] == "complete"
# df.loc[:, "par1"] = np.where(
#     df["status"] == "complete",
#     df["real"],
#     1200
# )
# df.loc[:, "par10"] = np.where(
#     df["status"] == "complete",
#     df["real"],
#     1200*10
# )

In [21]:
df["executable"].unique()

array(['amoclingo-amo-lg=c-r=nomin-l=f', 'amoclingo-amo-lg=c-r=nomin-l=t',
       'amoclingo-amo-lg=c-r=nomin-l=h',
       'amoclingo-amo-lg=py-r=nomin-l=f',
       'amoclingo-amo-lg=py-r=nomin-l=t',
       'amoclingo-amo-lg=py-r=nomin-l=h', 'amoclingo-eo-lg=c-r=nomin-l=f',
       'amoclingo-eo-lg=c-r=nomin-l=t', 'amoclingo-eo-lg=c-r=nomin-l=h',
       'amoclingo-eo-lg=py-r=nomin-l=f', 'amoclingo-eo-lg=py-r=nomin-l=t',
       'amoclingo-eo-lg=py-r=nomin-l=h', 'clingo-amo', 'clingo-eo',
       'wasp-amo', 'wasp-eo', 'amowasp-amo-lg=py-r=nomin-l=f',
       'amowasp-amo-lg=py-r=nomin-l=t', 'amowasp-amo-lg=py-r=nomin-l=h',
       'amowasp-eo-lg=py-r=nomin-l=f', 'amowasp-eo-lg=py-r=nomin-l=t',
       'amowasp-eo-lg=py-r=nomin-l=h', 'amoclingo-amo-base-lg=c',
       'amoclingo-amo-base-lg=py', 'amoclingo-eo-base-lg=c',
       'amoclingo-eo-base-lg=py', 'amowasp-amo-base-lg=py',
       'amowasp-eo-base-lg=py', 'amoclingo-amo-lg=c-r=ijcai-l=f',
       'amoclingo-amo-lg=py-r=ijcai-l=f', 'amoclingo-eo-lg=c-r=ijcai-l=f',
       'amoclingo-eo-lg=py-r=ijcai-l=f', 'amowasp-amo-lg=py-r=ijcai-l=f',
       'amowasp-eo-lg=py-r=ijcai-l=f', 'amoclingo-amo-lg=c-r=minfly-l=f',
       'amoclingo-amo-lg=c-r=minfly-l=t',
       'amoclingo-amo-lg=c-r=minfly-l=h',
       'amoclingo-eo-lg=c-r=minfly-l=f', 'amoclingo-eo-lg=c-r=minfly-l=t',
       'amoclingo-eo-lg=c-r=minfly-l=h'], dtype=object)

In [22]:
df[(df["problem"] == "Knapsack") & (df["executable"].str.contains("-amo-"))].sort_values("real")

,problem,instance,executable,full_instance,status,exit_code,real,time,user,system,memory,solved
4404,Knapsack,0004-knapsack-10-21938-2349242-type2.asp,amoclingo-amo-lg=c-r=nomin-l=h,results/Knapsack/0004-knapsack-10-21938-234924...,complete,20,0.295,0.11,0.11,0.00,30.9,True
4400,Knapsack,0000-knapsack-10-22288-53089-type1.asp,amoclingo-amo-lg=c-r=nomin-l=h,results/Knapsack/0000-knapsack-10-22288-53089-...,complete,10,0.297,0.11,0.10,0.01,30.7,True
16572,Knapsack,0002-knapsack-10-21756-170352-type1.asp,amoclingo-amo-lg=c-r=ijcai-l=f,results/Knapsack/0002-knapsack-10-21756-170352...,complete,10,0.299,0.12,0.11,0.01,30.8,True
4202,Knapsack,0002-knapsack-10-21756-170352-type1.asp,amoclingo-amo-lg=c-r=nomin-l=f,results/Knapsack/0002-knapsack-10-21756-170352...,complete,10,0.300,0.12,0.11,0.01,30.6,True
4500,Knapsack,0000-knapsack-10-22288-53089-type1.asp,amoclingo-amo-lg=py-r=nomin-l=f,results/Knapsack/0000-knapsack-10-22288-53089-...,complete,10,0.304,0.12,0.10,0.02,31.8,True
...,...,...,...,...,...,...,...,...,...,...,...,...
11524,Knapsack,0039-knapsack-25-52442-751649-type4.asp,amowasp-amo-lg=py-r=nomin-l=h,results/Knapsack/0039-knapsack-25-52442-751649...,outof time,143,1206.135,1200.45,1200.37,0.08,75.6,False
11341,Knapsack,0056-knapsack-35-73533-914194-type3.asp,amowasp-amo-lg=py-r=nomin-l=f,results/Knapsack/0056-knapsack-35-73533-914194...,outof time,143,1206.285,1200.65,1200.45,0.20,165.2,False
11581,Knapsack,0096-knapsack-55-116028-1429327-type3.asp,amowasp-amo-lg=py-r=nomin-l=h,results/Knapsack/0096-knapsack-55-116028-14293...,outof time,143,1207.456,1200.22,1200.03,0.19,134.4,False
11316,Knapsack,0031-knapsack-25-50200-639537-type1.asp,amowasp-amo-lg=py-r=nomin-l=f,results/Knapsack/0031-knapsack-25-50200-639537...,outof time,143,1208.419,1200.17,1199.94,0.23,162.5,False
11563,Knapsack,0078-knapsack-45-93147-1350924-type4.asp,amowasp-amo-lg=py-r=nomin-l=h,results/Knapsack/0078-knapsack-45-93147-135092...,outof time,143,1210.194,1200.37,1200.31,0.06,67.4,False

In [6]:
df["executable"].unique()

array(['amoclingo-amo-lg=c-r=nomin-l=f', 'amoclingo-amo-lg=c-r=nomin-l=t',
       'amoclingo-amo-lg=c-r=nomin-l=h',
       'amoclingo-amo-lg=py-r=nomin-l=f',
       'amoclingo-amo-lg=py-r=nomin-l=t',
       'amoclingo-amo-lg=py-r=nomin-l=h', 'amoclingo-eo-lg=c-r=nomin-l=f',
       'amoclingo-eo-lg=c-r=nomin-l=t', 'amoclingo-eo-lg=c-r=nomin-l=h',
       'amoclingo-eo-lg=py-r=nomin-l=f', 'amoclingo-eo-lg=py-r=nomin-l=t',
       'amoclingo-eo-lg=py-r=nomin-l=h', 'clingo-amo', 'clingo-eo',
       'wasp-amo', 'wasp-eo', 'amowasp-amo-lg=py-r=nomin-l=f',
       'amowasp-amo-lg=py-r=nomin-l=t', 'amowasp-amo-lg=py-r=nomin-l=h',
       'amowasp-eo-lg=py-r=nomin-l=f', 'amowasp-eo-lg=py-r=nomin-l=t',
       'amowasp-eo-lg=py-r=nomin-l=h', 'amoclingo-amo-base-lg=c',
       'amoclingo-amo-base-lg=py', 'amoclingo-eo-base-lg=c',
       'amoclingo-eo-base-lg=py', 'amowasp-amo-base-lg=py',
       'amowasp-eo-base-lg=py', 'amoclingo-amo-lg=c-r=ijcai-l=f',
       'amoclingo-amo-lg=py-r=ijcai-l=f', 'amoclingo-eo-lg=c-r=ijcai-l=f',
       'amoclingo-eo-lg=py-r=ijcai-l=f', 'amowasp-amo-lg=py-r=ijcai-l=f',
       'amowasp-eo-lg=py-r=ijcai-l=f', 'amoclingo-amo-lg=c-r=minfly-l=f',
       'amoclingo-amo-lg=c-r=minfly-l=t',
       'amoclingo-amo-lg=c-r=minfly-l=h',
       'amoclingo-eo-lg=c-r=minfly-l=f', 'amoclingo-eo-lg=c-r=minfly-l=t',
       'amoclingo-eo-lg=c-r=minfly-l=h'], dtype=object)

# Df AMO

In [7]:
df_amo = df.copy()
df_amo.drop(index=df[df["executable"].str.contains(r"(-eo-|-eo$)")].index, inplace=True)
df_amo.loc[:, "executable"] = df_amo["executable"].str.replace("-amo-","-")
df_amo.loc[:, "executable"] = df_amo["executable"].str.replace("-amo$","", regex=True)
df_amo["executable"].unique()

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_10492/1363333655.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_amo.drop(index=df[df["executable"].str.contains(r"(-eo-|-eo$)")].index, inplace=True)

array(['amoclingo-lg=c-r=nomin-l=f', 'amoclingo-lg=c-r=nomin-l=t',
       'amoclingo-lg=c-r=nomin-l=h', 'amoclingo-lg=py-r=nomin-l=f',
       'amoclingo-lg=py-r=nomin-l=t', 'amoclingo-lg=py-r=nomin-l=h',
       'clingo', 'wasp', 'amowasp-lg=py-r=nomin-l=f',
       'amowasp-lg=py-r=nomin-l=t', 'amowasp-lg=py-r=nomin-l=h',
       'amoclingo-base-lg=c', 'amoclingo-base-lg=py',
       'amowasp-base-lg=py', 'amoclingo-lg=c-r=ijcai-l=f',
       'amoclingo-lg=py-r=ijcai-l=f', 'amowasp-lg=py-r=ijcai-l=f',
       'amoclingo-lg=c-r=minfly-l=f', 'amoclingo-lg=c-r=minfly-l=t',
       'amoclingo-lg=c-r=minfly-l=h'], dtype=object)

## Pivot AMO

In [8]:
# pivot_amo = df_amo.pivot_table(index=["executable"],columns=["problem"], values=["solved","par1", "par10"], aggfunc={"solved":"sum", "par1": "mean", "par10": "mean"}, margins=True, margins_name='Total', fill_value=0)
pivot_amo = df_amo.pivot_table(index=["executable"],columns=["problem"], values=["solved"], aggfunc={"solved":"sum"}, margins=True, margins_name='Total', fill_value=0)
pivot_amo = pivot_amo.reorder_levels([1,0], axis=1).sort_index(axis=1)
pivot_amo = pivot_amo.drop(index="Total")
# pivot_amo.loc[:, "solved"].astype(int)
for col in pivot_amo.columns[(pivot_amo.columns.get_level_values(1) == "solved")]:
    pivot_amo[col] = pivot_amo.loc[:, col].astype(int)

for col in pivot_amo.columns:
    pivot_amo[col] = pivot_amo.loc[:, col].round(2)
pivot_amo

problem                     GraphColouring GroupAssignment Knapsack  Total
                                    solved          solved   solved solved
executable
amoclingo-base-lg=c                    102             307       77    486
amoclingo-base-lg=py                    95             141       75    311
amoclingo-lg=c-r=ijcai-l=f             120             307       77    504
amoclingo-lg=c-r=minfly-l=f            123             306       75    504
amoclingo-lg=c-r=minfly-l=h            122             310       75    507
amoclingo-lg=c-r=minfly-l=t            179             314       75    568
amoclingo-lg=c-r=nomin-l=f             122             309       76    507
amoclingo-lg=c-r=nomin-l=h             122             308       76    506
amoclingo-lg=c-r=nomin-l=t             165             313       77    555
amoclingo-lg=py-r=ijcai-l=f            118             229       76    423
amoclingo-lg=py-r=nomin-l=f            115             230       75    420
amoclingo-lg=py-r=nomin-l=h            115             232       75    422
amoclingo-lg=py-r=nomin-l=t            120             212       73    405
amowasp-base-lg=py                      64              65       71    200
amowasp-lg=py-r=ijcai-l=f               87             105       72    264
amowasp-lg=py-r=nomin-l=f               81              99       72    252
amowasp-lg=py-r=nomin-l=h               82              99       72    253
amowasp-lg=py-r=nomin-l=t              103             118       71    292
clingo                                  60             238       48    346
wasp                                    60              57       14    131

In [9]:
def create_catcus_df(df_input: pd.DataFrame) -> pd.DataFrame:
    df_catcus = pd.DataFrame()
    for solver in df_input["executable"].unique():
        df_catcus[solver] = df_input[(df_input["executable"] == solver) & (df_input["solved"])]["real"].sort_values().reset_index(drop=True)
    return df_catcus

In [10]:
df_cactus_amo = create_catcus_df(df_amo)
df_cactus_amo.to_csv("plots/catcus_amo.csv")

# Df EO

In [11]:
df_eo = df.copy()
df_eo.drop(index=df[df["executable"].str.contains("(-amo-|-amo$)")].index, inplace=True)
df_eo.loc[:, "executable"] = df_eo["executable"].str.replace("-eo-","-")
df_eo.loc[:, "executable"] = df_eo["executable"].str.replace(r"-eo$","", regex=True)
df_eo

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_10492/3915652154.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_eo.drop(index=df[df["executable"].str.contains("(-amo-|-amo$)")].index, inplace=True)

,problem,instance,executable,full_instance,status,exit_code,real,time,user,system,memory,solved
1800,GraphColouring,0001-graph_colouring-125-0_1200.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,10,3.166,2.83,2.81,0.02,50.4,True
1801,GraphColouring,0001-graph_colouring-125-0_2400.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,10,3.647,3.33,3.30,0.03,50.3,True
1802,GraphColouring,0001-graph_colouring-125-0_3600.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,outof time,143,1203.190,1200.79,1200.48,0.31,278.3,False
1803,GraphColouring,0001-graph_colouring-125-0_4800.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,20,560.651,558.35,558.01,0.34,418.2,True
1804,GraphColouring,0001-graph_colouring-125-0_6000.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,20,6.137,5.72,5.69,0.03,98.4,True
...,...,...,...,...,...,...,...,...,...,...,...,...
21095,Nurse,10nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/10nurses.asp.out,outof time,143,1201.440,1201.03,1200.39,0.64,522.1,False
21096,Nurse,164nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/164nurses.asp.out,outof memory,143,48.806,48.15,42.34,5.81,9593.4,False
21097,Nurse,20nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/20nurses.asp.out,outof time,143,1201.254,1200.44,1198.41,2.03,1443.6,False
21098,Nurse,41nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/41nurses.asp.out,outof time,143,1202.063,1200.56,1197.47,3.09,2676.1,False
21099,Nurse,82nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/82nurses.asp.out,outof time,143,1201.251,1200.10,1193.36,6.74,6554.5,False

In [13]:
df_cactus_eo = create_catcus_df(df_eo)
df_cactus_eo.to_csv("plots/catcus_eo.csv")

## Pivot EO

In [14]:
# pivot_eo = df_eo.pivot_table(index=["executable"],columns=["problem"], values=["solved","par1", "par10"], aggfunc={"solved":"sum", "par1": "mean", "par10": "mean"}, margins=True, margins_name='Total', fill_value=0)
pivot_eo = df_eo.pivot_table(index=["executable"],columns=["problem"], values=["solved"], aggfunc={"solved":"sum"}, margins=True, margins_name='Total', fill_value=0)
pivot_eo = pivot_eo.reorder_levels([1,0], axis=1).sort_index(axis=1)
pivot_eo = pivot_eo.drop(index="Total")

for col in pivot_eo.columns[(pivot_eo.columns.get_level_values(1) == "solved")]:
    pivot_eo[col] = pivot_eo.loc[:, col].astype(int)
pivot_eo

problem                     GraphColouring  Nurse  Total
                                    solved solved solved
executable
amoclingo-base-lg=c                    101      1    102
amoclingo-base-lg=py                    79      0     79
amoclingo-lg=c-r=ijcai-l=f             153      1    154
amoclingo-lg=c-r=minfly-l=f            131      0    131
amoclingo-lg=c-r=minfly-l=h            132      0    132
amoclingo-lg=c-r=minfly-l=t            169      1    170
amoclingo-lg=c-r=nomin-l=f             157      1    158
amoclingo-lg=c-r=nomin-l=h             160      1    161
amoclingo-lg=c-r=nomin-l=t             172      3    175
amoclingo-lg=py-r=ijcai-l=f            101      1    102
amoclingo-lg=py-r=nomin-l=f             96      1     97
amoclingo-lg=py-r=nomin-l=h             99      1    100
amoclingo-lg=py-r=nomin-l=t            100      1    101
amowasp-base-lg=py                      50      0     50
amowasp-lg=py-r=ijcai-l=f               86      0     86
amowasp-lg=py-r=nomin-l=f               86      0     86
amowasp-lg=py-r=nomin-l=h               86      0     86
amowasp-lg=py-r=nomin-l=t               85      0     85
clingo                                  95      4     99
wasp                                    32      0     32

# Latex Functions

In [15]:
import subprocess
from pathlib import Path
import shutil

def create_latex_visualization(latex_input: str, output_dir: str, output_name, tex_name: str = "main"):
    latex = rf"""
            \documentclass{{article}}
            \usepackage{{booktabs}}
            \usepackage{{multirow}}
            \pagestyle{{empty}}
            \begin{{document}}
            {latex_input}
            \end{{document}}
            """
    output_path = Path(f"{output_dir}/{output_name}")
    output_path.mkdir(parents=True, exist_ok=True)
    tex_name = f"{tex_name}.tex"
    tex_file = output_path / tex_name
    tex_file.write_text(latex)
    subprocess.run(
        ["/Library/TeX/texbin/pdflatex", tex_name],
        cwd=output_path
    )

## Cactus

In [16]:
def create_cactus_latex(file: str, legend_style: str = "at={(1.25,1.0)},anchor=north,fill=none", xmin=0, xmax=None, ymin=0, ymax=1200, subset_solvers = None):
    
    df_cac = pd.read_csv(file, sep=",", header="infer")
    def get_style_plot(solver: str):
        style = {}

        if re.search("amoclingo",solver):
            style["color"] = "blue"
        elif re.search("amowasp", solver):
            style["color"] = "yellow"
        elif re.search("^clingo", solver):
            style["color"] = "red"
        elif re.search("^wasp", solver):
            style["color"] = "green"
        else:
            raise Exception(f"Invalid Solver: {solver}")
        
        if re.search("amoclingo",solver):
            style["mark"] = "o"
        elif re.search("amowasp", solver):
            style["mark"] = "o"
        elif re.search("^clingo", solver):
            style["mark"] = "+"
        elif re.search("^wasp", solver):
            style["mark"] = "+"
        else:
            raise Exception(f"Invalid Solver: {solver}")
        
        return style 
    
    plot_lines = []
    columns = list(df_cac.columns)
    for i in range(1, len(columns)):
        solver = columns[i]
        if not subset_solvers is None and not solver in subset_solvers: continue
        plot_line = []
        style = get_style_plot(solver)
        plot_line = f"""
            \\addplot [mark size=2pt, color={style['color']}, mark={style['mark']}] [unbounded coords=jump] table[col sep=comma, y index={i}] {{./{file}}};
            \\addlegendentry{{{solver}}}
            """
        plot_lines.append(plot_line)

    xmax_str = f"xmax={xmax}" if xmax else ""
    tex_catctus = f"""  
    \\begin{{tikzpicture}}[scale=0.7]
        \\pgfkeys{{/pgf/number format/set thousands separator = {{}}}}
        \\begin{{axis}}[
        scale only axis
        , xlabel={{Solved instances}}
        , ylabel={{Time (s)}}    
        , xmin=0, {xmax_str}
        , ymin=0, ymax=1220
        , legend style={legend_style}
        , legend columns=1
        , width=0.65\\textwidth
        , height=0.40\\textwidth
        , major tick length=2pt
        , title= {{Catctus Plot}}
        ]

        {'\n'.join(plot_lines)}            

        \\end{{axis}}
    \\end{{tikzpicture}}%
    """
    return tex_catctus

catcus_latex_amo = create_cactus_latex("plots/catcus_amo.csv", subset_solvers=["clingo", "wasp", "amoclingo-lg=c-r=minfly-l=t"])
print(catcus_latex_amo)

    \begin{tikzpicture}[scale=0.7]
        \pgfkeys{/pgf/number format/set thousands separator = {}}
        \begin{axis}[
        scale only axis
        , xlabel={Solved instances}
        , ylabel={Time (s)}
        , xmin=0,
        , ymin=0, ymax=1220
        , legend style=at={(1.25,1.0)},anchor=north,fill=none
        , legend columns=1
        , width=0.65\textwidth
        , height=0.40\textwidth
        , major tick length=2pt
        , title= {Catctus Plot}
        ]


            \addplot [mark size=2pt, color=red, mark=+] [unbounded coords=jump] table[col sep=comma, y index=7] {./plots/catcus_amo.csv};
            \addlegendentry{clingo}


            \addplot [mark size=2pt, color=green, mark=+] [unbounded coords=jump] table[col sep=comma, y index=8] {./plots/catcus_amo.csv};
            \addlegendentry{wasp}


            \addplot [mark size=2pt, color=blue, mark=o] [unbounded coords=jump] table[col sep=comma, y index=19] {./plots/catcus_amo.csv};
            \addlegendentry{amoclingo-lg=c-r=minfly-l=t}


        \end{axis}
    \end{tikzpicture}%

## Tables

In [17]:
def get_pivot_latex(pivot: pd.DataFrame):
    pivot_latex = pivot.copy()

    for c in pivot_latex.columns:
        maxVal = pivot_latex[c].max()
        pivot_latex[c] = pivot_latex[c].astype(object)
        for r in pivot_latex.index:
            v = pivot_latex.at[r, c]
            if v == maxVal:
                pivot_latex.at[r, c] = rf"\textbf{{{v}}}"
            else:
                pivot_latex.at[r, c] = str(v)
    display(pivot_latex)
    latex = pivot_latex.to_latex(
        multicolumn=True,           
        multicolumn_format='c',     
        multirow=True,              
        bold_rows=False,    
        na_rep='-',                 
        label="tab:results",
        position="t!",
        escape=False,               
    )
    return latex

table_amo_res = get_pivot_latex(pivot_amo)
print(table_amo_res)
create_latex_visualization(table_amo_res, "tables", "table_amo")

problem,GraphColouring,GroupAssignment,Knapsack,Total
,solved,solved,solved,solved
executable,,,,
amoclingo-base-lg=c,102,307,\textbf{77},486
amoclingo-base-lg=py,95,141,75,311
amoclingo-lg=c-r=ijcai-l=f,120,307,\textbf{77},504
amoclingo-lg=c-r=minfly-l=f,123,306,75,504
amoclingo-lg=c-r=minfly-l=h,122,310,75,507
amoclingo-lg=c-r=minfly-l=t,\textbf{179},\textbf{314},75,\textbf{568}
amoclingo-lg=c-r=nomin-l=f,122,309,76,507
amoclingo-lg=c-r=nomin-l=h,122,308,76,506
amoclingo-lg=c-r=nomin-l=t,165,313,\textbf{77},555
amoclingo-lg=py-r=ijcai-l=f,118,229,76,423
amoclingo-lg=py-r=nomin-l=f,115,230,75,420
amoclingo-lg=py-r=nomin-l=h,115,232,75,422
amoclingo-lg=py-r=nomin-l=t,120,212,73,405
amowasp-base-lg=py,64,65,71,200
amowasp-lg=py-r=ijcai-l=f,87,105,72,264
amowasp-lg=py-r=nomin-l=f,81,99,72,252
amowasp-lg=py-r=nomin-l=h,82,99,72,253
amowasp-lg=py-r=nomin-l=t,103,118,71,292
clingo,60,238,48,346
wasp,60,57,14,131

ImportError: Missing optional dependency 'Jinja2'. DataFrame.style requires jinja2. Use pip or conda to install Jinja2.