# Extract

In [162]:
import os
import pandas as pd

df = pd.read_csv("amosum_experiments_clown-version.csv", sep=",", header="infer")
df.drop(columns=["solver","type","version","lazy","lang","minimality","solved","par1","par10","status_1","status_2"], inplace=True)
df

,problem,instance,executable,full_instance,status,exit_code,real,time,user,system,memory
0,GraphColouring,0001-graph_colouring-125-0_1200.asp,B-clingo-amosum-amo-c,results/GraphColouring/0001-graph_colouring-12...,complete,10,0.689,0.51,0.48,0.03,50.1
1,GraphColouring,0001-graph_colouring-125-0_2400.asp,B-clingo-amosum-amo-c,results/GraphColouring/0001-graph_colouring-12...,outof time,143,1200.501,1200.12,1199.80,0.32,402.7
2,GraphColouring,0001-graph_colouring-125-0_3600.asp,B-clingo-amosum-amo-c,results/GraphColouring/0001-graph_colouring-12...,outof time,143,1201.594,1200.88,1200.21,0.67,513.0
3,GraphColouring,0001-graph_colouring-125-0_4800.asp,B-clingo-amosum-amo-c,results/GraphColouring/0001-graph_colouring-12...,outof time,143,1200.974,1200.64,1200.02,0.62,457.6
4,GraphColouring,0001-graph_colouring-125-0_6000.asp,B-clingo-amosum-amo-c,results/GraphColouring/0001-graph_colouring-12...,complete,20,9.802,9.17,9.11,0.06,122.1
...,...,...,...,...,...,...,...,...,...,...,...
46805,Nurse,10nurses.asp,fixedD-clingo-amosum-eo-c-hybrid,results/Nurse/10nurses.asp.out,outof time,143,1201.440,1201.03,1200.39,0.64,522.1
46806,Nurse,164nurses.asp,fixedD-clingo-amosum-eo-c-hybrid,results/Nurse/164nurses.asp.out,outof memory,143,48.806,48.15,42.34,5.81,9593.4
46807,Nurse,20nurses.asp,fixedD-clingo-amosum-eo-c-hybrid,results/Nurse/20nurses.asp.out,outof time,143,1201.254,1200.44,1198.41,2.03,1443.6
46808,Nurse,41nurses.asp,fixedD-clingo-amosum-eo-c-hybrid,results/Nurse/41nurses.asp.out,outof time,143,1202.063,1200.56,1197.47,3.09,2676.1
46809,Nurse,82nurses.asp,fixedD-clingo-amosum-eo-c-hybrid,results/Nurse/82nurses.asp.out,outof time,143,1201.251,1200.10,1193.36,6.74,6554.5

In [163]:
df["executable"].unique()

array(['B-clingo-amosum-amo-c', 'B-clingo-amosum-amo-c-full',
       'C-clingo-amosum-amo-c-full-min', 'B-clingo-amosum-amo-c-hybrid',
       'B-clingo-amosum-amo-py', 'B-clingo-amosum-amo-py-full',
       'B-clingo-amosum-amo-py-hybrid', 'B-clingo-amosum-eo-c',
       'B-clingo-amosum-eo-c-full', 'C-clingo-amosum-eo-c-full-min',
       'B-clingo-amosum-eo-c-hybrid', 'B-clingo-amosum-eo-py',
       'B-clingo-amosum-eo-py-full', 'B-clingo-amosum-eo-py-hybrid',
       'clingo-plain-amo', 'clingo-plain-eo', 'wasp-plain-amo',
       'wasp-plain-eo', 'B-wasp-amosum-amo-py',
       'B-wasp-amosum-amo-py-full', 'C-wasp-amosum-amo-py-full-min',
       'B-wasp-amosum-amo-py-hybrid', 'B-wasp-amosum-eo-py',
       'B-wasp-amosum-eo-py-full', 'C-wasp-amosum-eo-py-full-min',
       'B-wasp-amosum-eo-py-hybrid', 'ijcai-clingo-amosum-amo-c',
       'ijcai-clingo-amosum-amo-py', 'ijcai-clingo-amosum-eo-c',
       'ijcai-clingo-amosum-eo-py', 'ijcai-wasp-amosum-amo-py',
       'ijcai-wasp-amosum-eo-py', 'D-clingo-amosum-amo-c',
       'D-clingo-amosum-amo-c-full', 'D-clingo-amosum-amo-c-hybrid',
       'D-clingo-amosum-amo-py', 'D-clingo-amosum-amo-py-full',
       'D-clingo-amosum-amo-py-hybrid', 'D-clingo-amosum-eo-c',
       'D-clingo-amosum-eo-c-full', 'D-clingo-amosum-eo-c-hybrid',
       'D-clingo-amosum-eo-py', 'D-clingo-amosum-eo-py-full',
       'D-clingo-amosum-eo-py-hybrid', 'D-wasp-amosum-amo-py',
       'D-wasp-amosum-amo-py-full', 'D-wasp-amosum-amo-py-hybrid',
       'D-wasp-amosum-eo-py', 'D-wasp-amosum-eo-py-full',
       'D-wasp-amosum-eo-py-hybrid', 'A-clingo-amosum-amo-c',
       'A-clingo-amosum-amo-py', 'A-clingo-amosum-eo-c',
       'A-clingo-amosum-eo-py', 'A-wasp-amosum-amo-py',
       'A-wasp-amosum-eo-py', 'fixedD-clingo-amosum-amo-c',
       'fixedD-clingo-amosum-amo-c-full',
       'fixedD-clingo-amosum-amo-c-hybrid', 'fixedD-clingo-amosum-eo-c',
       'fixedD-clingo-amosum-eo-c-full',
       'fixedD-clingo-amosum-eo-c-hybrid'], dtype=object)

In [164]:
df["problem"].unique()

array(['GraphColouring', 'Knapsack', 'GroupAssignment', 'Nurse'],
      dtype=object)

# Remove WASP and Clingo version

In [165]:
solver_mask_wasp_eo = df["executable"].str.contains("wasp-plain-eo")
solver_mask_clingo_eo = df["executable"].str.contains("clingo-plain-eo")

solver_mask_wasp_amo = df["executable"].str.contains("wasp-plain-amo")
solver_mask_clingo_amo = df["executable"].str.contains("clingo-plain-amo")

problem_mask_eo =  df["problem"].str.contains(r"(Knapsack|GroupAssignment)")
problem_mask_amo =  df["problem"].str.contains(r"Nurse")

df_cleaned = df.copy()
for solver_eo in [solver_mask_wasp_eo, solver_mask_clingo_eo]:
    df_cleaned.drop(index=df[solver_eo & problem_mask_eo].index, inplace=True)

for solver_amo in [solver_mask_wasp_amo, solver_mask_clingo_amo]:
    df_cleaned.drop(index=df[solver_amo & problem_mask_amo].index, inplace=True)

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/3070459918.py:7: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  problem_mask_eo =  df["problem"].str.contains(r"(Knapsack|GroupAssignment)")

# Remove AMOWASP and AMOCLINGO version

In [166]:
solver_mask_amowasp_eo = df["executable"].str.contains("wasp-amosum-eo")
solver_mask_amoclingo_eo = df["executable"].str.contains("clingo-amosum-eo")

solver_mask_amowasp_amo = df["executable"].str.contains("wasp-amosum-amo")
solver_mask_amoclingo_amo = df["executable"].str.contains("clingo-amosum-amo")

for solver_eo in [solver_mask_amowasp_eo, solver_mask_amoclingo_eo]:
    df_cleaned.drop(index=df[solver_eo & problem_mask_eo].index, inplace=True)

for solver_amo in [solver_mask_amowasp_amo, solver_mask_amoclingo_amo]:
    df_cleaned.drop(index=df[solver_amo & problem_mask_amo].index, inplace=True)

In [167]:
df_cleaned[df["executable"].str.contains("B-")]["executable"].unique()

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/3390962456.py:1: UserWarning: Boolean Series key will be reindexed to match DataFrame index.
  df_cleaned[df["executable"].str.contains("B-")]["executable"].unique()

array(['B-clingo-amosum-amo-c', 'B-clingo-amosum-amo-c-full',
       'B-clingo-amosum-amo-c-hybrid', 'B-clingo-amosum-amo-py',
       'B-clingo-amosum-amo-py-full', 'B-clingo-amosum-amo-py-hybrid',
       'B-clingo-amosum-eo-c', 'B-clingo-amosum-eo-c-full',
       'B-clingo-amosum-eo-c-hybrid', 'B-clingo-amosum-eo-py',
       'B-clingo-amosum-eo-py-full', 'B-clingo-amosum-eo-py-hybrid',
       'B-wasp-amosum-amo-py', 'B-wasp-amosum-amo-py-full',
       'B-wasp-amosum-amo-py-hybrid', 'B-wasp-amosum-eo-py',
       'B-wasp-amosum-eo-py-full', 'B-wasp-amosum-eo-py-hybrid'],
      dtype=object)

In [168]:
df_cleaned.drop(index=df_cleaned[df_cleaned["executable"].str.contains(r"^C-")].index, inplace=True)
df_cleaned.drop(index=df_cleaned[df_cleaned["executable"].str.contains(r"^D-")].index, inplace=True)
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"wasp-plain","wasp")
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"clingo-plain","clingo")
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"wasp-amosum","amowasp")
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"clingo-amosum","amoclingo")

# IJCAI
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"ijcai-(amoclingo|amowasp)-(amo|eo)-(py|c)",r"\1-\2-base-lg=\3", regex=True)

# Improved Inference and Activation progation
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"A-(amoclingo|amowasp)-(amo|eo)-(py|c)",r"\1-\2-lg=\3-r=ijcai-l=f", regex=True)

# Improved reason and lazy
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"B-(amoclingo|amowasp)-(amo|eo)-(py|c)$",r"\1-\2-lg=\3-r=nomin-l=f", regex=True)
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"B-(amoclingo|amowasp)-(amo|eo)-(py|c)-hybrid$",r"\1-\2-lg=\3-r=nomin-l=h", regex=True)
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"B-(amoclingo|amowasp)-(amo|eo)-(py|c)-full$",r"\1-\2-lg=\3-r=nomin-l=t", regex=True)

# Minimal reason on the fly and lazy
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"fixedD-(amoclingo|amowasp)-(amo|eo)-(py|c)$",r"\1-\2-lg=\3-r=minfly-l=f", regex=True)
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"fixedD-(amoclingo|amowasp)-(amo|eo)-(py|c)-hybrid$",r"\1-\2-lg=\3-r=minfly-l=h", regex=True)
df_cleaned.loc[:, "executable"] = df_cleaned.loc[:, "executable"].str.replace(r"fixedD-(amoclingo|amowasp)-(amo|eo)-(py|c)-full$",r"\1-\2-lg=\3-r=minfly-l=t", regex=True)

df_cleaned["executable"].unique()

array(['amoclingo-amo-lg=c-r=nomin-l=f', 'amoclingo-amo-lg=c-r=nomin-l=t',
       'amoclingo-amo-lg=c-r=nomin-l=h',
       'amoclingo-amo-lg=py-r=nomin-l=f',
       'amoclingo-amo-lg=py-r=nomin-l=t',
       'amoclingo-amo-lg=py-r=nomin-l=h', 'amoclingo-eo-lg=c-r=nomin-l=f',
       'amoclingo-eo-lg=c-r=nomin-l=t', 'amoclingo-eo-lg=c-r=nomin-l=h',
       'amoclingo-eo-lg=py-r=nomin-l=f', 'amoclingo-eo-lg=py-r=nomin-l=t',
       'amoclingo-eo-lg=py-r=nomin-l=h', 'clingo-amo', 'clingo-eo',
       'wasp-amo', 'wasp-eo', 'amowasp-amo-lg=py-r=nomin-l=f',
       'amowasp-amo-lg=py-r=nomin-l=t', 'amowasp-amo-lg=py-r=nomin-l=h',
       'amowasp-eo-lg=py-r=nomin-l=f', 'amowasp-eo-lg=py-r=nomin-l=t',
       'amowasp-eo-lg=py-r=nomin-l=h', 'amoclingo-amo-base-lg=c',
       'amoclingo-amo-base-lg=py', 'amoclingo-eo-base-lg=c',
       'amoclingo-eo-base-lg=py', 'amowasp-amo-base-lg=py',
       'amowasp-eo-base-lg=py', 'amoclingo-amo-lg=c-r=ijcai-l=f',
       'amoclingo-amo-lg=py-r=ijcai-l=f', 'amoclingo-eo-lg=c-r=ijcai-l=f',
       'amoclingo-eo-lg=py-r=ijcai-l=f', 'amowasp-amo-lg=py-r=ijcai-l=f',
       'amowasp-eo-lg=py-r=ijcai-l=f', 'amoclingo-amo-lg=c-r=minfly-l=f',
       'amoclingo-amo-lg=c-r=minfly-l=t',
       'amoclingo-amo-lg=c-r=minfly-l=h',
       'amoclingo-eo-lg=c-r=minfly-l=f', 'amoclingo-eo-lg=c-r=minfly-l=t',
       'amoclingo-eo-lg=c-r=minfly-l=h'], dtype=object)

# Computing Metrics

In [169]:
# solved,par1,par10
import numpy as np


df_cleaned.loc[:, "solved"] = df_cleaned["status"] == "complete"
df_cleaned.loc[:, "par1"] = np.where(
    df_cleaned["status"] == "complete",
    df_cleaned["real"],
    1200
)
df_cleaned.loc[:, "par10"] = np.where(
    df_cleaned["status"] == "complete",
    df_cleaned["real"],
    1200*10
)

In [170]:
df_cleaned["executable"].unique()

array(['amoclingo-amo-lg=c-r=nomin-l=f', 'amoclingo-amo-lg=c-r=nomin-l=t',
       'amoclingo-amo-lg=c-r=nomin-l=h',
       'amoclingo-amo-lg=py-r=nomin-l=f',
       'amoclingo-amo-lg=py-r=nomin-l=t',
       'amoclingo-amo-lg=py-r=nomin-l=h', 'amoclingo-eo-lg=c-r=nomin-l=f',
       'amoclingo-eo-lg=c-r=nomin-l=t', 'amoclingo-eo-lg=c-r=nomin-l=h',
       'amoclingo-eo-lg=py-r=nomin-l=f', 'amoclingo-eo-lg=py-r=nomin-l=t',
       'amoclingo-eo-lg=py-r=nomin-l=h', 'clingo-amo', 'clingo-eo',
       'wasp-amo', 'wasp-eo', 'amowasp-amo-lg=py-r=nomin-l=f',
       'amowasp-amo-lg=py-r=nomin-l=t', 'amowasp-amo-lg=py-r=nomin-l=h',
       'amowasp-eo-lg=py-r=nomin-l=f', 'amowasp-eo-lg=py-r=nomin-l=t',
       'amowasp-eo-lg=py-r=nomin-l=h', 'amoclingo-amo-base-lg=c',
       'amoclingo-amo-base-lg=py', 'amoclingo-eo-base-lg=c',
       'amoclingo-eo-base-lg=py', 'amowasp-amo-base-lg=py',
       'amowasp-eo-base-lg=py', 'amoclingo-amo-lg=c-r=ijcai-l=f',
       'amoclingo-amo-lg=py-r=ijcai-l=f', 'amoclingo-eo-lg=c-r=ijcai-l=f',
       'amoclingo-eo-lg=py-r=ijcai-l=f', 'amowasp-amo-lg=py-r=ijcai-l=f',
       'amowasp-eo-lg=py-r=ijcai-l=f', 'amoclingo-amo-lg=c-r=minfly-l=f',
       'amoclingo-amo-lg=c-r=minfly-l=t',
       'amoclingo-amo-lg=c-r=minfly-l=h',
       'amoclingo-eo-lg=c-r=minfly-l=f', 'amoclingo-eo-lg=c-r=minfly-l=t',
       'amoclingo-eo-lg=c-r=minfly-l=h'], dtype=object)

# Df AMO

In [171]:
df_amo = df_cleaned.copy()
df_amo.drop(index=df_cleaned[df_cleaned["executable"].str.contains(r"(-eo-|-eo$)")].index, inplace=True)
df_amo.loc[:, "executable"] = df_amo["executable"].str.replace("-amo-","-")
df_amo.loc[:, "executable"] = df_amo["executable"].str.replace("-amo$","", regex=True)
df_amo["executable"].unique()

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/116015588.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_amo.drop(index=df_cleaned[df_cleaned["executable"].str.contains(r"(-eo-|-eo$)")].index, inplace=True)

array(['amoclingo-lg=c-r=nomin-l=f', 'amoclingo-lg=c-r=nomin-l=t',
       'amoclingo-lg=c-r=nomin-l=h', 'amoclingo-lg=py-r=nomin-l=f',
       'amoclingo-lg=py-r=nomin-l=t', 'amoclingo-lg=py-r=nomin-l=h',
       'clingo', 'wasp', 'amowasp-lg=py-r=nomin-l=f',
       'amowasp-lg=py-r=nomin-l=t', 'amowasp-lg=py-r=nomin-l=h',
       'amoclingo-base-lg=c', 'amoclingo-base-lg=py',
       'amowasp-base-lg=py', 'amoclingo-lg=c-r=ijcai-l=f',
       'amoclingo-lg=py-r=ijcai-l=f', 'amowasp-lg=py-r=ijcai-l=f',
       'amoclingo-lg=c-r=minfly-l=f', 'amoclingo-lg=c-r=minfly-l=t',
       'amoclingo-lg=c-r=minfly-l=h'], dtype=object)

## Pivot AMO

In [172]:
pivot_amo = df_amo.pivot_table(index=["executable"],columns=["problem"], values=["solved","par1", "par10"], aggfunc={"solved":"sum", "par1": "mean", "par10": "mean"}, margins=True, margins_name='Total', fill_value=0)
pivot_amo = pivot_amo.reorder_levels([1,0], axis=1).sort_index(axis=1)
pivot_amo = pivot_amo.drop(index="Total")
# pivot_amo.loc[:, "solved"].astype(int)
for col in pivot_amo.columns[(pivot_amo.columns.get_level_values(1) == "solved")]:
    pivot_amo[col] = pivot_amo.loc[:, col].astype(int)
pivot_amo

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/2818900098.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pivot_amo[col] = pivot_amo.loc[:, col].astype(int)
/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/2818900098.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pivot_amo[col] = pivot_amo.loc[:, col].astype(int)
/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/2818900098.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pivot_amo[col] = pivot_amo.loc[:, col].astype(int)

problem                     GraphColouring                      \
                                      par1        par10 solved
executable
amoclingo-base-lg=c             829.086973  7957.086973    102
amoclingo-base-lg=py            879.518720  8259.518720     95
amoclingo-lg=c-r=ijcai-l=f      726.349797  7206.349797    120
amoclingo-lg=c-r=minfly-l=f     721.488780  7093.488780    123
amoclingo-lg=c-r=minfly-l=h     722.448423  7130.448423    122
amoclingo-lg=c-r=minfly-l=t     533.319137  4889.319137    179
amoclingo-lg=c-r=nomin-l=f      720.597563  7128.597563    122
amoclingo-lg=c-r=nomin-l=h      720.843153  7128.843153    122
amoclingo-lg=c-r=nomin-l=t      583.254720  5443.254720    165
amoclingo-lg=py-r=ijcai-l=f     763.867613  7315.867613    118
amoclingo-lg=py-r=nomin-l=f     769.641177  7429.641177    115
amoclingo-lg=py-r=nomin-l=h     771.777943  7431.777943    115
amoclingo-lg=py-r=nomin-l=t     726.249860  7206.249860    120
amowasp-base-lg=py             1040.805900  9536.805900     64
amowasp-lg=py-r=ijcai-l=f       964.450887  8632.450887     87
amowasp-lg=py-r=nomin-l=f       979.144813  8863.144813     81
amowasp-lg=py-r=nomin-l=h       977.604900  8825.604900     82
amowasp-lg=py-r=nomin-l=t       881.306327  7973.306327    103
clingo                          960.551110  9600.551110     60
wasp                            963.009267  9603.009267     60

problem                     GroupAssignment                         Knapsack  \
                                       par1         par10 solved        par1
executable
amoclingo-base-lg=c              265.191494   1592.048637    307   288.52475
amoclingo-base-lg=py             866.419551   7315.562409    141   322.49164
amoclingo-lg=c-r=ijcai-l=f       178.976109   1505.833251    307   282.97328
amoclingo-lg=c-r=minfly-l=f      202.135060   1559.849346    306   310.65843
amoclingo-lg=c-r=minfly-l=h      192.750209   1427.035923    310   311.64113
amoclingo-lg=c-r=minfly-l=t      231.161900   1342.019043    314   305.95175
amoclingo-lg=c-r=nomin-l=f       175.163814   1440.306671    309   295.93386
amoclingo-lg=c-r=nomin-l=h       177.557414   1473.557414    308   294.56715
amoclingo-lg=c-r=nomin-l=t       215.113106   1356.827391    313   289.62305
amoclingo-lg=py-r=ijcai-l=f      606.971603   4340.685889    229   305.88945
amoclingo-lg=py-r=nomin-l=f      610.478494   4313.335637    230   312.85060
amoclingo-lg=py-r=nomin-l=h      610.419017   4251.561874    232   312.71949
amoclingo-lg=py-r=nomin-l=t      669.486800   4927.772514    212   330.86381
amowasp-base-lg=py              1053.922651   9848.208366     65   355.89535
amowasp-lg=py-r=ijcai-l=f        935.348794   8495.348794    105   347.22068
amowasp-lg=py-r=nomin-l=f        956.970717   8702.113574     99   344.42229
amowasp-lg=py-r=nomin-l=h        956.100971   8701.243829     99   345.23617
amowasp-lg=py-r=nomin-l=t        921.878637   8080.735780    118   352.95756
clingo                           498.660714   3954.660714    238   631.38421
wasp                            1020.305546  10061.448403     57  1051.22643

problem                                                Total               \
                                   par10 solved         par1        par10
executable
amoclingo-base-lg=c           2772.52475     77   493.860787  4295.460787
amoclingo-base-lg=py          3022.49164     75   799.135497  7120.735497
amoclingo-lg=c-r=ijcai-l=f    2766.97328     77   411.791873  3954.191873
amoclingo-lg=c-r=minfly-l=f   3010.65843     75   424.346331  3966.746331
amoclingo-lg=c-r=minfly-l=h   3011.64113     75   420.481617  3919.681617
amoclingo-lg=c-r=minfly-l=t   3005.95175     75   361.996775  2982.796775
amoclingo-lg=c-r=nomin-l=f    2887.93386     76   409.439987  3908.639987
amoclingo-lg=c-r=nomin-l=h    2886.56715     76   410.473008  3924.073008
amoclingo-lg=c-r=nomin-l=t    2773.62305     77   372.304411  3180.304411
amoclingo-lg=py-r=ijcai-l=f   2897.88945     76   629.585720  5338.385720
amoclingo-lg=py-r=nomin-l=f   3012.85060     75   634.459848  5386.459848
amoclingo-lg=py-r=nomin-l=h   3012.71949     75   635.269317  5358.469317
amoclingo-lg=py-r=nomin-l=t   3246.86381     73   647.042292  5615.042292
amowasp-base-lg=py            3487.89535     71   955.605644  8875.605644
amowasp-lg=py-r=ijcai-l=f     3371.22068     72   868.572549  7866.972549
amowasp-lg=py-r=nomin-l=f     3368.42229     72   884.167232  8055.367232
amowasp-lg=py-r=nomin-l=h     3369.23617     72   883.253903  8040.053903
amowasp-lg=py-r=nomin-l=t     3484.95756     71   829.793569  7424.993569
clingo                        6247.38421     48   701.113339  6518.713339
wasp                         10339.22643     14  1001.509819  9915.109819

problem
                            solved
executable
amoclingo-base-lg=c            486
amoclingo-base-lg=py           311
amoclingo-lg=c-r=ijcai-l=f     504
amoclingo-lg=c-r=minfly-l=f    504
amoclingo-lg=c-r=minfly-l=h    507
amoclingo-lg=c-r=minfly-l=t    568
amoclingo-lg=c-r=nomin-l=f     507
amoclingo-lg=c-r=nomin-l=h     506
amoclingo-lg=c-r=nomin-l=t     555
amoclingo-lg=py-r=ijcai-l=f    423
amoclingo-lg=py-r=nomin-l=f    420
amoclingo-lg=py-r=nomin-l=h    422
amoclingo-lg=py-r=nomin-l=t    405
amowasp-base-lg=py             200
amowasp-lg=py-r=ijcai-l=f      264
amowasp-lg=py-r=nomin-l=f      252
amowasp-lg=py-r=nomin-l=h      253
amowasp-lg=py-r=nomin-l=t      292
clingo                         346
wasp                           131

# Df EO

In [173]:
df_eo = df_cleaned.copy()
df_eo.drop(index=df_cleaned[df_cleaned["executable"].str.contains("(-amo-|-amo$)")].index, inplace=True)
df_eo.loc[:, "executable"] = df_eo["executable"].str.replace("-eo-","-")
df_eo.loc[:, "executable"] = df_eo["executable"].str.replace(r"-eo$","")
df_eo

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/465205950.py:2: UserWarning: This pattern is interpreted as a regular expression, and has match groups. To actually get the groups, use str.extract.
  df_eo.drop(index=df_cleaned[df_cleaned["executable"].str.contains("(-amo-|-amo$)")].index, inplace=True)

,problem,instance,executable,full_instance,status,exit_code,real,time,user,system,memory,solved,par1,par10
2100,GraphColouring,0001-graph_colouring-125-0_1200.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,10,3.166,2.83,2.81,0.02,50.4,True,3.166,3.166
2101,GraphColouring,0001-graph_colouring-125-0_2400.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,10,3.647,3.33,3.30,0.03,50.3,True,3.647,3.647
2102,GraphColouring,0001-graph_colouring-125-0_3600.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,outof time,143,1203.190,1200.79,1200.48,0.31,278.3,False,1200.000,12000.000
2103,GraphColouring,0001-graph_colouring-125-0_4800.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,20,560.651,558.35,558.01,0.34,418.2,True,560.651,560.651
2104,GraphColouring,0001-graph_colouring-125-0_6000.asp,amoclingo-lg=c-r=nomin-l=f,results/GraphColouring/0001-graph_colouring-12...,complete,20,6.137,5.72,5.69,0.03,98.4,True,6.137,6.137
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46805,Nurse,10nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/10nurses.asp.out,outof time,143,1201.440,1201.03,1200.39,0.64,522.1,False,1200.000,12000.000
46806,Nurse,164nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/164nurses.asp.out,outof memory,143,48.806,48.15,42.34,5.81,9593.4,False,1200.000,12000.000
46807,Nurse,20nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/20nurses.asp.out,outof time,143,1201.254,1200.44,1198.41,2.03,1443.6,False,1200.000,12000.000
46808,Nurse,41nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/41nurses.asp.out,outof time,143,1202.063,1200.56,1197.47,3.09,2676.1,False,1200.000,12000.000
46809,Nurse,82nurses.asp,amoclingo-lg=c-r=minfly-l=h,results/Nurse/82nurses.asp.out,outof time,143,1201.251,1200.10,1193.36,6.74,6554.5,False,1200.000,12000.000

## Pivot EO

In [174]:
pivot_eo = df_eo.pivot_table(index=["executable"],columns=["problem"], values=["solved","par1", "par10"], aggfunc={"solved":"sum", "par1": "mean", "par10": "mean"}, margins=True, margins_name='Total', fill_value=0)
pivot_eo = pivot_eo.reorder_levels([1,0], axis=1).sort_index(axis=1)
pivot_eo = pivot_eo.drop(index="Total")

for col in pivot_eo.columns[(pivot_eo.columns.get_level_values(1) == "solved")]:
    pivot_eo[col] = pivot_eo.loc[:, col].astype(int)
pivot_eo

/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/486015992.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pivot_eo[col] = pivot_eo.loc[:, col].astype(int)
/var/folders/60/msx2m7995xv41v59mx28gt5w0000gn/T/ipykernel_3994/486015992.py:6: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  pivot_eo[col] = pivot_eo.loc[:, col].astype(int)

problem                     GraphColouring                           Nurse  \
                                      par1         par10 solved       par1
executable
amoclingo-base-lg=c             836.167800   8000.167800    101   978.1478
amoclingo-base-lg=py            949.293477   8905.293477     79  1200.0000
amoclingo-lg=c-r=ijcai-l=f      716.327030   6008.327030    153   976.0836
amoclingo-lg=c-r=minfly-l=f     757.259980   6841.259980    131  1200.0000
amoclingo-lg=c-r=minfly-l=h     755.028817   6803.028817    132  1200.0000
amoclingo-lg=c-r=minfly-l=t     628.139977   5344.139977    169   967.5678
amoclingo-lg=c-r=nomin-l=f      714.883767   5862.883767    157   976.0382
amoclingo-lg=c-r=nomin-l=h      712.737777   5752.737777    160   976.0730
amoclingo-lg=c-r=nomin-l=t      631.663240   5239.663240    172   739.6544
amoclingo-lg=py-r=ijcai-l=f     860.977173   8024.977173    101  1066.9706
amoclingo-lg=py-r=nomin-l=f     874.460777   8218.460777     96  1067.9438
amoclingo-lg=py-r=nomin-l=h     871.543283   8107.543283     99  1067.7274
amoclingo-lg=py-r=nomin-l=t     840.025563   8040.025563    100  1088.4696
amowasp-base-lg=py             1121.413147  10121.413147     50  1200.0000
amowasp-lg=py-r=ijcai-l=f       907.478657   8611.478657     86  1200.0000
amowasp-lg=py-r=nomin-l=f       904.055217   8608.055217     86  1200.0000
amowasp-lg=py-r=nomin-l=h       903.095013   8607.095013     86  1200.0000
amowasp-lg=py-r=nomin-l=t       890.770860   8630.770860     85  1200.0000
clingo-eo                       936.575023   8316.575023     95   434.8148
wasp-eo                        1093.406903  10741.406903     32  1200.0000

problem                                               Total                \
                                  par10 solved         par1         par10
executable
amoclingo-base-lg=c           9618.1478      1   838.495341   8026.692062
amoclingo-base-lg=py         12000.0000      0   953.403420   8956.026370
amoclingo-lg=c-r=ijcai-l=f    9616.0836      1   720.585334   6067.470580
amoclingo-lg=c-r=minfly-l=f  12000.0000      0   764.518013   6925.829489
amoclingo-lg=c-r=minfly-l=h  12000.0000      0   762.323426   6888.225066
amoclingo-lg=c-r=minfly-l=t   9607.5678      1   633.704367   5414.032236
amoclingo-lg=c-r=nomin-l=f    9616.0382      1   719.164987   5924.410889
amoclingo-lg=c-r=nomin-l=h    9616.0730      1   717.054748   5816.071141
amoclingo-lg=c-r=nomin-l=t    5059.6544      3   633.433587   5236.712275
amoclingo-lg=py-r=ijcai-l=f   9706.9706      1   864.354115   8052.550836
amoclingo-lg=py-r=nomin-l=f   9707.9438      1   877.632630   8242.878531
amoclingo-lg=py-r=nomin-l=h   9707.7274      1   874.759416   8133.775810
amoclingo-lg=py-r=nomin-l=t   9728.4696      1   844.098416   8067.704974
amowasp-base-lg=py           12000.0000      0  1122.701456  10152.209652
amowasp-lg=py-r=ijcai-l=f    12000.0000      0   912.274089   8667.028187
amowasp-lg=py-r=nomin-l=f    12000.0000      0   908.906770   8663.660869
amowasp-lg=py-r=nomin-l=h    12000.0000      0   907.962308   8662.716407
amowasp-lg=py-r=nomin-l=t    12000.0000      0   895.840190   8686.004125
clingo-eo                     2594.8148      4   928.349446   8222.775675
wasp-eo                      12000.0000      0  1095.154331  10762.039577

problem
                            solved
executable
amoclingo-base-lg=c            102
amoclingo-base-lg=py            79
amoclingo-lg=c-r=ijcai-l=f     154
amoclingo-lg=c-r=minfly-l=f    131
amoclingo-lg=c-r=minfly-l=h    132
amoclingo-lg=c-r=minfly-l=t    170
amoclingo-lg=c-r=nomin-l=f     158
amoclingo-lg=c-r=nomin-l=h     161
amoclingo-lg=c-r=nomin-l=t     175
amoclingo-lg=py-r=ijcai-l=f    102
amoclingo-lg=py-r=nomin-l=f     97
amoclingo-lg=py-r=nomin-l=h    100
amoclingo-lg=py-r=nomin-l=t    101
amowasp-base-lg=py              50
amowasp-lg=py-r=ijcai-l=f       86
amowasp-lg=py-r=nomin-l=f       86
amowasp-lg=py-r=nomin-l=h       86
amowasp-lg=py-r=nomin-l=t       85
clingo-eo                       99
wasp-eo                         32